/* virtual icon manifest - generated by vite-plugin-icon-manifest */
export const iconLoaders = {
	book: () => import('@lucide/svelte/icons/book'),
	'book-open-check': () => import('@lucide/svelte/icons/book-open-check'),
	cog: () => import('@lucide/svelte/icons/cog'),
	component: () => import('@lucide/svelte/icons/component'),
	dices: () => import('@lucide/svelte/icons/dices'),
	flag: () => import('@lucide/svelte/icons/flag'),
	rocket: () => import('@lucide/svelte/icons/rocket')
};
export default iconLoaders;
