import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

export default function iconManifestPlugin(options?: {
	configPath?: string;
	virtualModuleId?: string;
}): Plugin {
	const configPath =
		options?.configPath ?? 'src/lib/docs/navigation/doc-navigation.config.server.ts';
	const virtualId = options?.virtualModuleId ?? 'virtual:icon-manifest';
	const resolvedVirtualId = '\0' + virtualId;
	let icons = new Set<string>();

	async function generate() {
		const p = path.resolve(process.cwd(), configPath);
		try {
			const source = fs.readFileSync(p, 'utf-8');
			const set = new Set<string>();
			// Find occurrences like: icon: 'name' or "name"
			const regex = /icon\s*:\s*['"]([a-zA-Z0-9_-]+)['"]/g;
			let m;
			while ((m = regex.exec(source)) !== null) {
				set.add(m[1].toLowerCase());
			}
			icons = set;
		} catch (e) {
			icons = new Set();
		}

		console.log(icons);
	}

	function generateModuleCode() {
		const entries = Array.from(icons)
			.sort()
			.map((name) => `"${name}": () => import("@lucide/svelte/icons/${name}")`);
		console.log(entries);
		return `/* virtual icon manifest - generated by vite-plugin-icon-manifest */\nexport const iconLoaders = {\n${entries.map((e) => '  ' + e).join(',\n')}\n};\nexport default iconLoaders;\n`;
	}

	return {
		name: 'vite-plugin-icon-manifest',
		enforce: 'pre',
		async buildStart() {
			await generate();
			this.addWatchFile(path.resolve(process.cwd(), configPath));
		},
		resolveId(id) {
			if (id === virtualId) return resolvedVirtualId;
		},
		load(id) {
			if (id === resolvedVirtualId) {
				console.log('loading id', id);
				return generateModuleCode();
			}
		},
		configureServer(server) {
			const p = path.resolve(process.cwd(), configPath);
			server.watcher.add(p);
			server.watcher.on('change', async (changed) => {
				if (changed === p) {
					await generate();
					// trigger full reload so modules using the virtual module pick up changes
					server.ws.send({ type: 'full-reload' });
				}
			});
		}
	};
}
