/**
 * Rehype plugin that rewrites <CodeGroup> children into tab primitives.
 *
 * Input shape:
 * - MDX JSX node named `CodeGroup` with fenced code blocks as children.
 *
 * Output shape:
 * - MDX JSX node named `Tabs` containing `TabsList`, `TabsTrigger`, and
 *   `TabsContent` children.
 *
 * Tab labels are resolved in this order:
 * 1) code block title (figure caption generated by rehype-pretty-code)
 * 2) parsed code fence metadata (e.g. `title=` or plain token)
 * 3) detected language
 * 4) fallback `tab-N`
 */
import type { Element, Root } from 'hast';
import { visit } from 'unist-util-visit';

type MdxAttribute = {
	name?: string;
	value?: unknown;
	[key: string]: unknown;
};

type MdxJsxNode = {
	type?: string;
	name?: string;
	attributes?: MdxAttribute[];
	children?: unknown[];
	[key: string]: unknown;
};

type CodeTab = {
	value: string;
	label: string;
	content: Element;
};

/** Builds an MDX JSX flow node. */
function createMdxNode(name: string, children: unknown[] = [], attributes: MdxAttribute[] = []): MdxJsxNode {
	return {
		type: 'mdxJsxFlowElement',
		name,
		attributes,
		children
	};
}

/** Builds a plain text node for trigger labels. */
function createMdxText(value: string): { type: 'text'; value: string } {
	return { type: 'text', value };
}

/** Recursively extracts text content from a rehype node subtree. */
function extractText(node: unknown): string {
	if (
		typeof node === 'object' &&
		node !== null &&
		(node as { type?: unknown }).type === 'text' &&
		typeof (node as { value?: unknown }).value === 'string'
	) {
		return (node as { value: string }).value;
	}

	if (typeof node !== 'object' || node === null || !Array.isArray((node as { children?: unknown[] }).children)) {
		return '';
	}

	return (node as { children: unknown[] }).children.map((child) => extractText(child)).join('');
}

/** Trims and strips wrapping single/double quotes from a label token. */
function sanitizeLabel(label: string): string {
	return label.replaceAll(/^['"]|['"]$/g, '').trim();
}

/**
 * Parses a user-visible label from fence metadata.
 * Supports `title="..."` first, then a plain token fallback.
 */
function parseMetaLabel(meta: string): string {
	if (!meta) return '';

	const titleMatch = /(?:^|\s)title=(?:"([^"]+)"|'([^']+)'|([^\s]+))/.exec(meta);
	if (titleMatch) {
		return sanitizeLabel(titleMatch[1] ?? titleMatch[2] ?? titleMatch[3] ?? '');
	}

	const tokens = meta.split(/\s+/).map((token) => sanitizeLabel(token)).filter(Boolean);

	for (const token of tokens) {
		if (token.includes('=')) continue;
		if (/^\{.*\}$/.test(token)) continue;
		if (token.startsWith('showLineNumbers')) continue;
		return token;
	}

	return '';
}

function isElement(node: unknown): node is Element {
	return typeof node === 'object' && node !== null && (node as { type?: unknown }).type === 'element';
}

function isMdxJsxNode(node: unknown): node is MdxJsxNode {
	if (typeof node !== 'object' || node === null) return false;
	const typeValue = (node as { type?: unknown }).type;
	return typeof typeValue === 'string' && typeValue.startsWith('mdxJsx');
}

function findPreElement(block: Element): Element | undefined {
	if (block.tagName === 'pre') return block;
	return block.children.find((child) => isElement(child) && child.tagName === 'pre') as
		| Element
		| undefined;
}

/** Reads metadata from the first code node in a code block container. */
function getCodeMeta(block: Element): string {
	const pre = findPreElement(block);
	const code = pre?.children.find((child) => isElement(child) && child.tagName === 'code') as
		| Element
		| undefined;
	if (!code) return '';

	const metaFromData = typeof code.data?.meta === 'string' ? code.data.meta : '';
	const metaFromAttr = typeof code.properties?.['data-meta'] === 'string' ? code.properties['data-meta'] : '';
	return (metaFromAttr || metaFromData || '').trim();
}

/** Resolves the language hint from `pre` or nested `code` properties. */
function getCodeLanguage(block: Element): string {
	const pre = findPreElement(block);
	if (!pre) return '';

	const preLanguage = pre.properties?.['data-language'];
	if (typeof preLanguage === 'string' && preLanguage.trim()) return preLanguage;

	const code = pre.children.find((child) => isElement(child) && child.tagName === 'code') as
		| Element
		| undefined;
	const codeLanguage = code?.properties?.['data-language'];
	return typeof codeLanguage === 'string' ? codeLanguage.trim() : '';
}

/**
 * Reads the human-facing title generated by rehype-pretty-code for a figure.
 */
function getTitleFromFigure(block: Element): string {
	if (block.tagName !== 'figure') return '';

	const titleNode = block.children.find(
		(child) =>
			isElement(child) &&
			child.tagName === 'figcaption' &&
			Object.hasOwn(child.properties ?? {}, 'data-rehype-pretty-code-title')
	) as Element | undefined;

	if (!titleNode) return '';

	return sanitizeLabel(extractText(titleNode).trim());
}

/**
 * Removes figure title captions before embedding the block in TabsContent,
 * since the title is promoted into the tab label.
 */
function cloneWithoutFigureTitle(block: Element): Element {
	if (block.tagName !== 'figure') return block;

	return {
		...block,
		children: block.children.filter(
			(child) =>
				!(
					isElement(child) &&
					child.tagName === 'figcaption' &&
					Object.hasOwn(child.properties ?? {}, 'data-rehype-pretty-code-title')
				)
		)
	};
}

/** Chooses the tab label using title -> metadata -> language -> fallback. */
function resolveTabLabel(block: Element, index: number): string {
	const titleLabel = getTitleFromFigure(block);
	if (titleLabel) return titleLabel;

	const metaLabel = parseMetaLabel(getCodeMeta(block));
	if (metaLabel) return metaLabel;

	const language = getCodeLanguage(block);
	if (language) return language;

	return `tab-${index + 1}`;
}

/** True when node is a code block we can place in a tab panel. */
function isCodeBlockChild(node: unknown): node is Element {
	if (!isElement(node)) return false;
	if (node.tagName === 'pre') return true;

	return (
		node.tagName === 'figure' &&
		Object.hasOwn(node.properties ?? {}, 'data-rehype-pretty-code-figure')
	);
}

/**
 * Factory for the CodeGroup-to-Tabs AST transform.
 */
export function rehypeTransformCodeGroup() {
	return (root: Root) => {
		visit(root, (node: unknown) => {
			if (!isMdxJsxNode(node) || node.name !== 'CodeGroup') {
				return;
			}

			const codeBlocks = (node.children ?? []).filter(isCodeBlockChild);
			if (codeBlocks.length === 0) {
				return;
			}

			const seen: Record<string, number> = {};
			const tabs: CodeTab[] = codeBlocks.map((block, index) => {
				const baseLabel = resolveTabLabel(block, index);
				const count = seen[baseLabel] ?? 0;
				seen[baseLabel] = count + 1;
				const label = count === 0 ? baseLabel : `${baseLabel}-${count + 1}`;

				return {
					value: label,
					label,
					content: cloneWithoutFigureTitle(block)
				};
			});

			const tabsList = createMdxNode(
				'TabsList',
				tabs.map((tab) =>
					createMdxNode('TabsTrigger', [createMdxText(tab.label)], [{ name: 'value', value: tab.value }])
				)
			);

			const tabsContent = tabs.map((tab) =>
				createMdxNode('TabsContent', [tab.content], [{ name: 'value', value: tab.value }])
			);

			node.name = 'Tabs';
			node.attributes = [
				...(node.attributes ?? []).filter((attr) => attr.name !== 'value'),
				{ name: 'value', value: tabs[0]?.value ?? '' }
			];
			node.children = [tabsList, ...tabsContent];
		});
	};
}
